### `.str` (Vectorized String Operations)

It is used to perform **string operations on entire Pandas Series efficiently** (without using loops).


#### Syntax
    df['column'].str.method()


| Method        | Description                                      | Example                          |
|---------------|--------------------------------------------------|----------------------------------|
| lower()       | Convert to lowercase                             | str.lower()                      |
| upper()       | Convert to uppercase                             | str.upper()                      |
| title()       | Convert to title case                            | str.title()                      |
| strip()       | Remove leading/trailing spaces                   | str.strip()                      |
| lstrip()      | Remove left spaces                               | str.lstrip()                     |
| rstrip()      | Remove right spaces                              | str.rstrip()                     |
| replace()     | Replace substring                                | str.replace('a','b')             |
| contains()    | Check substring presence                         | str.contains('abc')              |
| startswith()  | Check prefix                                     | str.startswith('A')              |
| endswith()    | Check suffix                                     | str.endswith('z')                |
| len()         | Length of string                                 | str.len()                        |
| split()       | Split string                                     | str.split(',')                   |
| get()         | Extract element from split                       | str.split(',').str.get(0)        |
| extract()     | Extract using regex                              | str.extract('(\d+)')             |
| find()        | Find substring position                          | str.find('x')                    |

In [1]:
import pandas as pd

In [2]:
titanic_data = pd.read_csv('titanic.csv')

In [3]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Make 3 columns from Name, i.e., Salutaion, First Name and Last Name

In [4]:
titanic_data['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
titanic_data['Name'].str.split(',') #splitted first on the basis of ',' because the first one is the last name

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [9]:
titanic_data['Last_Name'] = titanic_data['Name'].str.split(',').str.get(0)

In [10]:
titanic_data['Last_Name']

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Last_Name, Length: 891, dtype: object

In [ ]:
titanic_data['Name'].str.split(',').str.get(1).str.split('.') #splitted on the basis of '.', because the first one is the salutation

0                                 [ Mr,  Owen Harris]
1      [ Mrs,  John Bradley (Florence Briggs Thayer)]
2                                     [ Miss,  Laina]
3              [ Mrs,  Jacques Heath (Lily May Peel)]
4                               [ Mr,  William Henry]
                            ...
886                                   [ Rev,  Juozas]
887                          [ Miss,  Margaret Edith]
888                [ Miss,  Catherine Helen "Carrie"]
889                               [ Mr,  Karl Howell]
890                                   [ Mr,  Patrick]
Name: Name, Length: 891, dtype: object

In [16]:
titanic_data['Salutation'] = titanic_data['Name'].str.split(',').str.get(1).str.split('.').str.get(0)

In [17]:
titanic_data['Salutation']

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: Salutation, Length: 891, dtype: object

In [18]:
titanic_data['First_Name'] = titanic_data['Name'].str.split(',').str.get(1).str.split('.').str.get(1)

In [19]:
titanic_data['First_Name']

0                                 Owen Harris
1       John Bradley (Florence Briggs Thayer)
2                                       Laina
3               Jacques Heath (Lily May Peel)
4                               William Henry
                        ...
886                                    Juozas
887                            Margaret Edith
888                  Catherine Helen "Carrie"
889                               Karl Howell
890                                   Patrick
Name: First_Name, Length: 891, dtype: object

In [20]:
titanic_data[['Salutation', 'First_Name', 'Last_Name']]

    Salutation                              First_Name  Last_Name
0           Mr                             Owen Harris     Braund
1          Mrs   John Bradley (Florence Briggs Thayer)    Cumings
2         Miss                                   Laina  Heikkinen
3          Mrs           Jacques Heath (Lily May Peel)   Futrelle
4           Mr                           William Henry      Allen
..         ...                                     ...        ...
886        Rev                                  Juozas   Montvila
887       Miss                          Margaret Edith     Graham
888       Miss                Catherine Helen "Carrie"   Johnston
889         Mr                             Karl Howell       Behr
890         Mr                                 Patrick     Dooley

[891 rows x 3 columns]

### Find out the person whose First_Name have 'x'

In [24]:
titanic_data[titanic_data['First_Name'].str.contains('x')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Salutation,First_Name
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S,Fortune,Mr,Charles Alexander
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,52.0000,NaN,S,Holverson,Mr,Alexander Oskar
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C,Harper,Mrs,Henry Sleeper (Myna Haxtun)
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S,Andersson,Miss,Erna Alexandra
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.00,1,0,A/5. 3337,14.5000,NaN,S,Robins,Mrs,Alexander A (Grace Charity Laury)
224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,1,0,19943,90.0000,C93,S,Hoyt,Mr,Frederick Maxfield
243,244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22.00,0,0,STON/O 2. 3101275,7.1250,NaN,S,Maenpaa,Mr,Matti Alexanteri
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,Asplund,Master,Edvin Rojj Felix
270,271,0,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,Cairns,Mr,Alexander
383,384,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.00,1,0,113789,52.0000,NaN,S,Holverson,Mrs,Alexander Oskar (Mary Aline Towner)
432,433,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.00,1,0,SC/AH 3085,26.0000,NaN,S,Louch,Mrs,Charles Alexander (Alice Adelaide Slow)
486,487,1,1,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.00,1,0,19943,90.0000,C93,S,Hoyt,Mrs,Frederick Maxfield (Jane Anne Forby)
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.00,1,1,13567,79.2000,B41,C,Frolicher-Stehli,Mr,Maxmillian
632,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.00,0,0,13214,30.5000,B50,C,Stahelin-Maeglin,Dr,Max
656,657,0,3,"Radeff, Mr. Alexander",male,NaN,0,0,349223,7.8958,NaN,S,Radeff,Mr,Alexander
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S,Madill,Miss,Georgette Alexandra
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,Thomas,Master,Assad Alexander
818,819,0,3,"Holm, Mr. John Fredrik Alexander",male,43.00,0,0,C 7075,6.4500,NaN,S,Holm,Mr,John Fredrik Alexander
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C,Yasbeck,Mrs,Antoni (Selini Alexander)
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.00,0,1,11767,83.1583,C50,C,Potter,Mrs,Thomas Jr (Lily Alexenia Wilson)

### Find the person whose last name starts with 'P'

In [26]:
titanic_data[titanic_data['Last_Name'].str.startswith('P')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Last_Name,Salutation,First_Name
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Palsson,Master,Gosta Leonard
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,Palsson,Miss,Torborg Danira
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,Panula,Master,Juha Niilo
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S,Petranec,Miss,Matilda
101,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S,Petroff,Mr,"Pastcho (""Pentcho"")"
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S,Porter,Mr,Walter Chamberlain
115,116,0,3,"Pekoniemi, Mr. Edvard",male,21.0,0,0,STON/O 2. 3101294,7.9250,NaN,S,Pekoniemi,Mr,Edvard
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C,Peter,Miss,Anna
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S,Pears,Mrs,Thomas (Edith Wearne)
164,165,0,3,"Panula, Master. Eino Viljami",male,1.0,4,1,3101295,39.6875,NaN,S,Panula,Master,Eino Viljami
181,182,0,2,"Pernot, Mr. Rene",male,NaN,0,0,SC/PARIS 2131,15.0500,NaN,C,Pernot,Mr,Rene
190,191,1,2,"Pinsky, Mrs. (Rosa)",female,32.0,0,0,234604,13.0000,NaN,S,Pinsky,Mrs,(Rosa)
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S,Perkin,Mr,John Henry
238,239,0,2,"Pengelly, Mr. Frederick William",male,19.0,0,0,28665,10.5000,NaN,S,Pengelly,Mr,Frederick William
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,NaN,S,Parrish,Mrs,(Lutie Davis)
266,267,0,3,"Panula, Mr. Ernesti Arvid",male,16.0,4,1,3101295,39.6875,NaN,S,Panula,Mr,Ernesti Arvid
267,268,1,3,"Persson, Mr. Ernst Ulrik",male,25.0,1,0,347083,7.7750,NaN,S,Persson,Mr,Ernst Ulrik
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0000,NaN,S,Parkes,Mr,"Francis ""Frank"""
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,1,0,PC 17758,108.9000,C65,C,Penasco y Castellana,Mrs,Victor de Satode (Maria Josefa Perez de Soto ...
331,332,0,1,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S,Partner,Mr,Austen
336,337,0,1,"Pears, Mr. Thomas Clinton",male,29.0,1,0,113776,66.6000,C2,S,Pears,Mr,Thomas Clinton
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.0750,NaN,S,Palsson,Miss,Stina Viola
384,385,0,3,"Plotcharsky, Mr. Vasil",male,NaN,0,0,349227,7.8958,NaN,S,Plotcharsky,Mr,Vasil
398,399,0,2,"Pain, Dr. Alfred",male,23.0,0,0,244278,10.5000,NaN,S,Pain,Dr,Alfred
427,428,1,2,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.0,0,0,250655,26.0000,NaN,S,Phillips,Miss,"Kate Florence (""Mrs Kate Louise Phillips Mars..."
429,430,1,3,"Pickard, Mr. Berk (Berk Trembisky)",male,32.0,0,0,SOTON/O.Q. 392078,8.0500,E10,S,Pickard,Mr,Berk (Berk Trembisky)
442,443,0,3,"Petterson, Mr. Johan Emil",male,25.0,1,0,347076,7.7750,NaN,S,Petterson,Mr,Johan Emil
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S,Peuchen,Major,Arthur Godfrey
454,455,0,3,"Peduzzi, Mr. Joseph",male,NaN,0,0,A/5 2817,8.0500,NaN,S,Peduzzi,Mr,Joseph
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.0,1,0,PC 17758,108.9000,C65,C,Penasco y Castellana,Mr,Victor de Satode
519,520,0,3,"Pavlovic, Mr. Stefo",male,32.0,0,0,349242,7.8958,NaN,S,Pavlovic,Mr,Stefo
520,521,1,1,"Perreault, Miss. Anne",female,30.0,0,0,12749,93.5000,B73,S,Perreault,Miss,Anne
533,534,1,3,"Peter, Mrs. Catherine (Catherine Rizk)",female,NaN,0,2,2668,22.3583,NaN,C,Peter,Mrs,Catherine (Catherine Rizk)
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C,Padro y Manent,Mr,Julian
567,568,0,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.0750,NaN,S,Palsson,Mrs,Nils (Alma Cornelia Berglund)
575,576,0,3,"Patchett, Mr. George",male,19.0,0,0,358585,14.5000,NaN,S,Patchett,Mr,George
584,585,0,3,"Paulner, Mr. Uscher",male,NaN,0,0,3411,8.7125,NaN,C,Paulner,Mr,Uscher
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S,Parr,Mr,William Henry Marsh
638,639,0,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,3101295,39.6875,NaN,S,Panula,Mrs,Juha (Maria Emilia Ojala)
680,681,0,3,"Peters, Miss. Katie",female,NaN,0,0,330935,8.1375,NaN,Q,Peters,Miss,Katie
686,687,0,3,"Panula, Mr. Jaako Arnold",male,14.0,4,1,3101295,39.6875,NaN,S,Panula,Mr,Jaako Arnold
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S,Ponesell,Mr,Martin
807,808,0,3,"Pettersson, Miss. Ellen Natalia",female,18.0,0,0,347087,7.7750,NaN,S,Pettersson,Miss,Ellen Natalia
824,825,0,3,"Panula, Master. Urho Abraham",male,2.0,4,1,3101295,39.6875,NaN,S,Panula,Master,Urho Abraham
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S,Pasic,Mr,Jakob
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S,Petroff,Mr,Nedelio
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Potter,Mrs,Thomas Jr (Lily Alexenia Wilson)